version: '3.7'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME= 'root'
      - MONGO_INITDB_ROOT_PASSWORD= 'root'
      - MONGO_INITDB_DATABASE= 'database'
    volumes:
      - ./data:/data/db
    networks:
      - app-network
  app:
    container_name: node-app
    restart: always
    build: .
    ports:
      - '8080:8080'
    environment:
      - MONGO_USERNAME= 'root'
      - MONGO_PASSWORD= 'root'
      - MONGO_URI= 'mongo:27017/database
      - JWT_SECRET='9a8s7d6f5g4h3j2k1l'
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
